### ISSUE TITLE
Deploy to GitHub Pages

### ISSUE THREAD

**Issue by taiki-e** [openrr/openrr-tutorial#4]
Basically similar to https://github.com/openrr/openrr/commit/55c70ad63a5de717ee7145505dbd0ab4db9cd230. Something like the following: 

```yaml
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install mdbook
        uses: taiki-e/install-action@mdbook
      - run: mdbook build docs/en
      - run: mdbook build docs/ja
      - name: Deploy
        run: |
          mkdir -p book
          mv docs/en/book book/en
          mv docs/ja/book book/ja
          cd book
          git init
          git add .
          git -c user.name='ci' -c user.email='ci' commit -m 'Deploy OpenRR Book'
          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main' && github.repository_owner == 'openrr'
```
